// <auto-generated />
using System;
using Efs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Efs.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250308095153_initialize")]
    partial class initialize
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Efs.Models.AvailableStock", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id"));

                    b.Property<string>("cartridge_colour")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cartridge_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cartridge_partno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("issue_quantity")
                        .HasColumnType("int");

                    b.Property<string>("printer_brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("printer_model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("stock_quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("availableStock");
                });

            modelBuilder.Entity("Efs.Models.CartridgeDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cartridge_colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cartridge_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cartridge_partNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("printer_brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("printer_model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("stock_quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("cartridgeDetail");
                });

            modelBuilder.Entity("Efs.Models.IssuedDetail", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id"));

                    b.Property<string>("cartridge_colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cartridge_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cartridge_partno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("issued_quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("issuedDetails");
                });

            modelBuilder.Entity("Efs.Models.RequestCartridge", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("id"));

                    b.Property<string>("cartridge_colour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cartridge_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cartridge_partNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("printer_brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("printer_model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("required_quantity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("requestCartridge");
                });

            modelBuilder.Entity("Efs.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
